### ISSUE TITLE
Rename Italic instances to Roman instances

### ISSUE THREAD

**Issue by m4rc1e** [Omnibus-Type/Sansita-Swashed#2]
Google Fonts cannot accept a family if it only contains Italic styles. At the moment, this family has Light Italic to Black Italic styles. We need to drop Italic from each style name.

**Comment by Omnibus-Type** [comment]
Hi @m4rc1e do you suggest that we make the adjustment? or prefer to do it yourselves to avoid any complication in the publication process, We understand that @yanone had already made some adjustments and we only did the merge and rebase and make a comment to clarify the metric relationship with Sansita. We'll be waiting for your comments about it.

**Comment by RosaWagner** [comment]
Hi guys, Yanone is in holidays so I take the case. I can take care of the re-naming and adapting the build script accordingly if you don't see a problem with that.

**Comment by Omnibus-Type** [comment]
Perfect @RosaWagner we are glad to have your collaboration. Many thanks!
